In [21]:
import torch
# import numpy as np

In [17]:
# The type of tensor

# tensor
print(torch.tensor([[1,2],[3,4]]))
print('------------------------')

# GPU tensor
print(torch.tensor([[1,2],[3,4]], device="cuda:0"))
print('------------------------')

# float tensor
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
------------------------
tensor([[1, 2],
        [3, 4]], device='cuda:0')
------------------------
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [22]:
# tensor to ndarray 

temp = torch.tensor([[1,2],[3,4]])
# tensor
print(temp)
print(type(temp))
print('------------------------')

# ndarray: the array of numpy
print(temp.numpy())
print(type(temp.numpy()))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
------------------------
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [31]:
# transform the memory cpu to gpu

# cpu to gpu
cpu_temp = torch.tensor([[1,2],[3,4]], device="cpu:0")
print(cpu_temp)
print(cpu_temp.to("cuda"))
print('------------------------')

# gpu to cpu
gpu_temp = torch.tensor([[1,2],[3,4]], device="cuda:0")
print(gpu_temp)
print(gpu_temp.to("cpu"))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
------------------------
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1, 2],
        [3, 4]])


In [32]:
temp = torch.FloatTensor([1, 2, 3, 4, 5, 6, 7])
print(temp[0], temp[1], temp[-1])
print('------------------------')
print(temp[2:5], temp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


In [33]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([3, 4, 6])
print(w - v)

tensor([2, 2, 3])


In [37]:
# transform the memory cpu to gpu

temp = torch.tensor([[1, 2], [3, 4]])

print(temp.shape)
print('------------------------')

# transform the tensor to [4, 1]
print(temp.view(4, 1))
print('------------------------')

# transform the tensor to [1, :]
print(temp.view(-1))
print('------------------------')

# transform the tensor to [1, ?]
print(temp.view(1, -1))
print('------------------------')

# transform the tensor to [?, 1]
print(temp.view(-1, 1))

torch.Size([2, 2])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])
------------------------
tensor([1, 2, 3, 4])
------------------------
tensor([[1, 2, 3, 4]])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])
